Document: libjreen
Title: Debian libjreen Manual
Author: <insert document author here>
Abstract: This manual describes what libjreen is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libjreen/libjreen.sgml.gz

Format: postscript
Files: /usr/share/doc/libjreen/libjreen.ps.gz

Format: text
Files: /usr/share/doc/libjreen/libjreen.text.gz

Format: HTML
Index: /usr/share/doc/libjreen/html/index.html
Files: /usr/share/doc/libjreen/html/*.html
